-- People often copy jobs. When they do, the GM table does not exist anymore.
-- This line makes the job code work both inside and outside of gamemode files.
-- You should not copy this line into your code.
local GAMEMODE = GAMEMODE or GM
--[[--------------------------------------------------------
Default teams. Please do not edit this file. Please use the darkrpmod addon instead.
--------------------------------------------------------]]
---EMS 

TEAM_EMT = DarkRP.createJob("Emergency Medical Technician", {
   color = Color(0, 232, 255, 255),
   model = {"models/redninja/pmedic01.mdl"},
   description = [[]],
   weapons = {"med_kit"},
   command = "emt",
   max = 4,
   salary = 140,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = false,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "EMS",
})

TEAM_DOCTOR = DarkRP.createJob("Doctor", {
   color = Color(0, 232, 255, 255),
   model = {"models/redninja/pmedic01.mdl"},
   description = [[]],
   weapons = {"med_kit", "darkrp_defibrillator"},
   command = "doc",
   max = 1,
   salary = 300,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = false,
   -- CustomCheck
   medic = true,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "EMS",
})

TEAM_PARMEDIC = DarkRP.createJob("Paramedic", {
   color = Color(0, 232, 255, 255),
   model = {"models/redninja/pmedic01.mdl"},
   description = [[]],
   weapons = {"med_kit", "darkrp_defibrillator"},
   command = "pmedic",
   max = 2,
   salary = 280,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = false,
   -- CustomCheck
   medic = true,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "EMS",
})

--- Citizens 

TEAM_SANTA = DarkRP.createJob("Santa Calws", {
   color = Color(255, 0, 221, 255),
   model = {"models/player/christmas/santa.mdl"},
   description = [[HO HO HO]],
   weapons = {},
   command = "santa",
   max = 1,
   salary = 125,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "VIP",
})


TEAM_MECHANIC = DarkRP.createJob("Mechanic", {
   color = Color(255, 0, 221, 255),
   model = {"models/player/alyx.mdl"},
   description = [[Fix cars and make money!]],
   weapons = {"vc_wrench"},
   command = "Mechanic",
   max = 2,
   salary = 125,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Citizens",
})

TEAM_HMANAGER = DarkRP.createJob("Hotel Manager", {
   color = Color(255, 0, 221, 255),
   model = {"models/suits/male_01_open_tie.mdl"},
   description = [[You run the hotel and sell rooms!]],
   weapons = {"m9k_fists"},
   command = "Hotel",
   max = 2,
   salary = 125,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Citizens",
})

TEAM_GARBAGE = DarkRP.createJob("Garbage Man", {
   color = Color(255, 0, 221, 255),
   model = {"models/player/Group01/male_04.mdl"},
   description = [[Pick up the garbage off the streets and keel them clean!]],
   weapons = {"sw_trashbag", "sw_dumpster"},
   command = "Garabage",
   max = 1,
   salary = 50,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Citizens",
})

TEAM_CITIZEN = DarkRP.createJob("Citizen", {
    color = Color(20, 150, 20, 255),
    model = {
        "models/player/Group01/Female_01.mdl",
        "models/player/Group01/Female_02.mdl",
        "models/player/Group01/Female_03.mdl",
        "models/player/Group01/Female_04.mdl",
        "models/player/Group01/Female_06.mdl",
        "models/player/group01/male_01.mdl",
        "models/player/Group01/Male_02.mdl",
        "models/player/Group01/male_03.mdl",
        "models/player/Group01/Male_04.mdl",
        "models/player/Group01/Male_05.mdl",
        "models/player/Group01/Male_06.mdl",
        "models/player/Group01/Male_07.mdl",
        "models/player/Group01/Male_08.mdl",
        "models/player/Group01/Male_09.mdl"
    },
    description = [[The Citizen is the most basic level of society you can hold besides being a hobo. You have no specific role in city life.]],
    weapons = {"weapon_arc_atmcard"},
    command = "Citizen",
    max = 0,
    salary = GAMEMODE.Config.normalsalary,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Citizens",
})

--- Badies 

TEAM_PROSTITUTE = DarkRP.createJob("Prostitute", {
   color = Color(255, 0, 0, 255),
   model = {"models/player/Group01/Female_02.mdl"},
   description = [[You go around having sex for money.]],
   weapons = {"weapon_rape", "weapon_cuff_elastic"},
   command = "prostitute",
   max = 1,
   salary = 45,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Citizens",
})

TEAM_KKK = DarkRP.createJob("KKK Hitman", {
   color = Color(0, 2, 255, 255),
   model = {"models/player/kkkman.mdl"},
   description = [[Kill them all buy taking hits. Jews may be shot on sight w/ hits.]],
   weapons = {"weapon_arc_atmcard", "m9k_ak47", "m9k_knife", "keypad_cracker"},
   command = "kkk",
   max = 1,
   salary = 125,
   admin = 0,
   vote = true,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Gangsters",
})



--- Fire Department

TEAM_FIREFIGHTER = DarkRP.createJob("FireFighter", {
   color = Color(0, 232, 255, 255),
   model = {"models/fearless/fireman2.mdl"},
   description = [[]],
   weapons = {"weapon_extinguisher"},
   command = "ff",
   max = 4,
   salary = 140,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = false,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Fire Department",
})

TEAM_FIRECHIEF = DarkRP.createJob("Fire Chief", {
   color = Color(0, 232, 255, 255),
   model = {"models/fearless/fireman2.mdl"},
   description = [[]],
   weapons = {"weapon_extinguisher"},
   command = "fc",
   max = 1,
   salary = 300,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = false,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Fire Department",
})

TEAM_FIREASSIST = DarkRP.createJob("Assistant Fire Chief", {
   color = Color(0, 232, 255, 255),
   model = {"models/fearless/fireman2.mdl"},
   description = [[Radio Number is 1301]],
   weapons = {"weapon_extinguisher", "m9k_fists"},
   command = "afc",
   max = 1,
   salary = 140,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = false,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Fire Department",
})

TEAM_FMARSHALL = DarkRP.createJob("Fire Marshal", {
   color = Color(0, 232, 255, 255),
   model = {"models/fearless/fireman2.mdl"},
   description = [[]],
   weapons = {"weapon_extinguisher", "m9k_fists"},
   command = "fm",
   max = 1,
   salary = 140,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = false,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Fire Department",
})


--- Govorment Jobs

TEAM_POLICE = DarkRP.createJob("Police", {
    color = Color(25, 25, 170, 255),
    model = {"models/player/police.mdl", "models/player/police_fem.mdl"},
    description = [[The protector of every citizen that lives in the city.
        You have the power to arrest criminals and protect innocents.
        Hit a player with your arrest baton to put them in jail.
        Bash a player with a stunstick and they may learn to obey the law.
        The Battering Ram can break down the door of a criminal, with a warrant for their arrest.
        The Battering Ram can also unfreeze frozen props (if enabled).
        Type /wanted <name> to alert the public to the presence of a criminal.]],
    weapons = {"arrest_stick", "unarrest_stick", "m9k_m92beretta", "stunstick", "door_ram", "weaponchecker", "weapon_cuff_police"},
    command = "Police",
    max = 4,
    salary = GAMEMODE.Config.normalsalary * 1.45,
    admin = 0,
    vote = true,
    hasLicense = true,
    ammo = {
        ["pistol"] = 60,
    },
    category = "Civil Protection",
})

TEAM_SS = DarkRP.createJob("Secret Service", {
   color = Color(0, 2, 255, 255),
   model = {"models/player/urban.mdl"},
   description = [[You Protect the highest rank of authority ex. Mayor]],
   weapons = {"m9k_deagle", "m9k_m16a4_acog", "arrest_stick", "weaponchecker", "stunstick", "weapon_cuff_police"},
   command = "ss",
   max = 2,
   salary = 450,
   admin = 0,
   vote = true,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "VIP",
   customCheck = function(ply) return
   table.HasValue({"vip", "silvervip", "goldvip", "coowner", "owner", "headdeveloper"}, ply:GetNWString("usergroup"))
end,
CustomCheckFailMsg = "This Job is vip only.",
})

TEAM_TRUMP = DarkRP.createJob("Donald Trump", {
   color = Color(0, 2, 243, 264),
   model = {"models/player/donald_trump.mdl"},
   description = [[You are the President and the boss of the mayor!]],
   weapons = {},
   command = "donald",
   max = 1,
   salary = 1000,
   admin = 0,
   vote = true,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = true,
   hobo = false,
   cook = false,
   category = "VIP",
   customCheck = function(ply) return
   table.HasValue({"vip", "silvervip", "goldvip", "coowner", "owner", "headdeveloper"}, ply:GetNWString("usergroup"))
end,
CustomCheckFailMsg = "This Job is vip only.",
})

TEAM_SWAT = DarkRP.createJob("S.W.A.T Commander", {
   color = Color(0, 232, 255, 255),
   model = {"models/player/bfh_enforcer.mdl"},
   description = [[Radio Number is 1301]],
   weapons = {"weapon_cuff_tactical", "m9k_fists", "m9k_m416", "m9k_sig_p229r"},
   command = "scm",
   max = 1,
   salary = 200,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = false,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "S.W.A.T",
})

TEAM_SWAT = DarkRP.createJob("S.W.A.T", {
   color = Color(0, 232, 255, 255),
   model = {"models/player/bfh_operator.mdl"},
   description = [[Radio Number is 1301]],
   weapons = {"m9k_fists", "m9k_m416", "m9k_sig_p229r", "weapon_cuff_tactical"},
   command = "swat",
   max = 4,
   salary = 200,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = false,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "S.W.A.T",
})

TEAM_SWAT = DarkRP.createJob("S.W.A.T Medic", {
   color = Color(0, 232, 255, 255),
   model = {"models/player/bfh_mechanic.mdl"},
   description = [[Radio Number is 1301]],
   weapons = {"m9k_fists", "m9k_m416", "med_kit", "darkrp_defibrillator", "m9k_sig_p229r", "weapon_cuff_tactical"},
   command = "swatm",
   max = 2,
   salary = 150,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = false,
   -- CustomCheck
   medic = true,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "S.W.A.T",
})

---Staff Jobs

TEAM_ADMIN = DarkRP.createJob("Owner On Duty", {
   color = Color(0, 232, 255, 255),
   model = {"models/player/mnu_assault.mdl"},
   description = [[]],
   weapons = {"weapon_arc_atmcard", "unarrest_stick", "weaponchecker", "weapon_keypadchecker"},
   command = "Owner",
   max = 4,
   salary = 200,
   admin = 1,
   vote = false,
   hasLicense = true,
   candemote = false,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Other",
   customCheck = function(ply) return
   table.HasValue({"coowner", "owner"}, ply:GetNWString("usergroup"))
end,
CustomCheckFailMsg = "This Job is Developers only.",
})

TEAM_ADMIN = DarkRP.createJob("Developer On Duty", {
   color = Color(0, 232, 255, 255),
   model = {"models/player/mnu_assault.mdl"},
   description = [[]],
   weapons = {"weapon_arc_atmcard", "unarrest_stick", "weaponchecker", "weapon_keypadchecker"},
   command = "Developer",
   max = 2,
   salary = 45,
   admin = 1,
   vote = false,
   hasLicense = true,
   candemote = false,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Other",
   customCheck = function(ply) return
   table.HasValue({"developer", "headdeveloper", "owner"}, ply:GetNWString("usergroup"))
end,
CustomCheckFailMsg = "This Job is Developers only.",
})

TEAM_MANAGER = DarkRP.createJob("Manager On Duty", {
   color = Color(0, 232, 255, 255),
   model = {"models/player/mnu_assault.mdl"},
   description = [[]],
   weapons = {"weapon_arc_atmcard", "unarrest_stick", "weaponchecker", "weapon_keypadchecker"},
   command = "Manager",
   max = 1,
   salary = 100,
   admin = 1,
   vote = false,
   hasLicense = true,
   candemote = false,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Other",
   customCheck = function(ply) return
   table.HasValue({"comanager", "manager", "communitymanager", "owner"}, ply:GetNWString("usergroup"))
end,
CustomCheckFailMsg = "This Job is admin only.",0
})

TEAM_MODERATOR = DarkRP.createJob("Moderator On Duty", {
   color = Color(0, 232, 255, 255),
   model = {"models/player/mnu_assault.mdl"},
   description = [[]],
   weapons = {"weapon_arc_atmcard", "unarrest_stick", "weaponchecker", "weapon_keypadchecker"},
   command = "Moderator",
   max = 4,
   salary = 140,
   admin = 1,
   vote = false,
   hasLicense = true,
   candemote = false,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Other",
   customCheck = function(ply) return
   table.HasValue({"trialmoderator", "moderator", "headmoderator", "owner"}, ply:GetNWString("usergroup"))
end,
CustomCheckFailMsg = "This Job is for T-Mods and Mods only.",
})

TEAM_ADMIN = DarkRP.createJob("Admin On Duty", {
   color = Color(0, 232, 255, 255),
   model = {"models/player/mnu_assault.mdl"},
   description = [[]],
   weapons = {"weapon_arc_atmcard", "unarrest_stick", "weaponchecker", "weapon_keypadchecker"},
   command = "Admin",
   max = 4,
   salary = 45,
   admin = 1,
   vote = false,
   hasLicense = true,
   candemote = false,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Other",
   customCheck = function(ply) return
   table.HasValue({"admin", "eliteadmin", "headadmin", "superadmin", "headmoderator", "owner"}, ply:GetNWString("usergroup"))
end,
CustomCheckFailMsg = "This Job is Admins only.",
})

-- Compatibility for when default teams are disabled
TEAM_CITIZEN = TEAM_CITIZEN  or -1
TEAM_POLICE  = TEAM_POLICE   or -1
TEAM_GANG    = TEAM_GANG     or -1
TEAM_MOB     = TEAM_MOB      or -1
TEAM_GUN     = TEAM_GUN      or -1
TEAM_MEDIC   = TEAM_MEDIC    or -1
TEAM_CHIEF   = TEAM_CHIEF    or -1
TEAM_MAYOR   = TEAM_MAYOR    or -1
TEAM_HOBO    = TEAM_HOBO     or -1
TEAM_COOK    = TEAM_COOK     or -1

-- Door groups
AddDoorGroup("Cops and Mayor only", TEAM_CHIEF, TEAM_POLICE, TEAM_MAYOR, TEAM_SWAT, TEAM_SS)
AddDoorGroup("Gundealer only", TEAM_GUN)
AddDoorGroup("Hotel Manager", TEAM_HMANAGER)


-- Agendas
--DarkRP.createAgenda("Mafia agenda", TEAM_MOB, {TEAM_GANG})
--DarkRP.createAgenda("Police agenda", {TEAM_MAYOR, TEAM_CHIEF}, {TEAM_POLICE, TEAM_SWAT})

-- Group chats
DarkRP.createGroupChat(function(ply) return ply:isCP() end)
DarkRP.createGroupChat(TEAM_MOB, TEAM_GANG)
DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)

-- Initial team when first spawning
GAMEMODE.DefaultTeam = TEAM_CITIZEN

-- Teams that belong to Civil Protection
GAMEMODE.CivilProtection = {
    [TEAM_POLICE] = true,
    [TEAM_CHIEF] = true,
    [TEAM_MAYOR] = true,
    [TEAM_TRUMP] = true,
	[TEAM_SWAT] = true,
}

-- Hitman team
DarkRP.addHitmanTeam(TEAM_MOB)
DarkRP.addHitmanTeam(TEAM_KKK)

-- Demote groups
DarkRP.createDemoteGroup("Cops", {TEAM_POLICE, TEAM_CHIEF, TEAM_SWAT, TEAM_SS})
DarkRP.createDemoteGroup("Gangsters", {TEAM_GANG, TEAM_MOB})

-- Default categories
DarkRP.createCategory{
    name = "Citizens",
    categorises = "jobs",
    startExpanded = true,
    color = Color(0, 107, 0, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 100,
}

DarkRP.createCategory{
    name = "Civil Protection",
    categorises = "jobs",
    startExpanded = true,
    color = Color(25, 25, 170, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 101,
}

DarkRP.createCategory{
    name = "VIP",
    categorises = "jobs",
    startExpanded = true,
    color = Color(0, 107, 0, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 255,
}

DarkRP.createCategory{
    name = "Other",
    categorises = "jobs",
    startExpanded = true,
    color = Color(0, 107, 0, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 255,
}

